server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://D:/java/Miguel-Moreno/configs
          default-label: master


