server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    registry-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 3000 #solo lo usamos en desarrollo evita el error de que el ms esta caido